name: ci

on:
  schedule:
    - cron: '0 3 * * *'
  push:
    branches:
      - 'main'

jobs:
  docker:
    runs-on: ubuntu-latest
    name: build for amd64
    steps:
      -
        name: Checkout
        uses: actions/checkout@v4
      -
        name: Cancel Previous Runs
        uses: styfle/cancel-workflow-action@0.12.1
        with:
          all_but_latest: true
          access_token: ${{ secrets.GIT_TOKEN }}
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      -
        name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: .
          platforms: linux/amd64
          push: true
          tags: encodev/svtav1enc:hdr
